export const DAY_IN_MILLISECONDS = 24 * 60 * 60 * 1000;
export const PAYMENT_PARTITION_KEY_PREFIX = "PAYMENT#";
export const OWNED_PRODUCT_PARTITION_KEY_PREFIX = "OWNED_PRODUCT#";
export const PAYMENT_SORT_KEY_PREFIX = "PAYMENT#";
export const PURCHASE_SORT_KEY_PREFIX = "PURCHASE#";