# ---------------------------------------------------------------------------
# outputs.tf
#
# This file defines the values this module EXPOSES to its callers.
#
# Key concepts for beginners:
#
#   output "name" { value = ... }
#     Makes a computed value visible outside the module.
#     The caller accesses it as: module.<module_label>.<output_name>
#
#   Outputs serve several purposes:
#     1. Connect modules — e.g. pass the distribution ARN to a WAF module.
#     2. Drive further Terraform logic — e.g. use domain_name in Route53.
#     3. Provide runtime information — e.g. "terraform output" after apply.
#     4. Reduce duplication — callers don't need to copy-paste ARNs.
#
#   sensitive = true (not used here) would hide the value in plan/apply output
#   and make the caller mark it sensitive in their own outputs if referenced.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Core distribution identifiers
# ---------------------------------------------------------------------------

# distribution_id
# The unique identifier CloudFront assigns to the distribution.
# Used in AWS CLI commands, CloudFront invalidation requests, and WAF rules.
# Example: "E1234567890ABC"
output "distribution_id" {
  description = "CloudFront distribution ID."
  value       = aws_cloudfront_distribution.this.id
}

# distribution_arn
# The full Amazon Resource Name of the distribution.
# Used when attaching AWS WAF Web ACLs, resource policies, or tagging by ARN.
# Example: "arn:aws:cloudfront::123456789012:distribution/E1234567890ABC"
output "distribution_arn" {
  description = "CloudFront distribution ARN."
  value       = aws_cloudfront_distribution.this.arn
}

# distribution_domain_name
# The autogenerated *.cloudfront.net hostname.
# Always resolvable, even without custom domains.
# Use this directly, or as the ALIAS target in Route53 records.
# Example: "d111111abcdef8.cloudfront.net"
output "distribution_domain_name" {
  description = "CloudFront distribution domain name."
  value       = aws_cloudfront_distribution.this.domain_name
}

# hosted_zone_id
# The AWS hosted zone ID for CloudFront — constant across all distributions.
# Required when creating a Route53 alias record pointing to this distribution.
# The value is always "Z2FDTNDATAQYW2" for CloudFront.
# Terraform reads it from the live resource so you don't need to hard-code it.
output "hosted_zone_id" {
  description = "CloudFront hosted zone ID for Route53 alias records."
  value       = aws_cloudfront_distribution.this.hosted_zone_id
}

# ---------------------------------------------------------------------------
# Origin access control
# ---------------------------------------------------------------------------

# origin_access_control_id
# The OAC identifier: either the module-created OAC or the pre-existing one
# passed in via var.origin_access_control.id.
# Expose this so the same OAC can be reused across multiple distributions
# without re-creating it (pass it back in as origin_access_control.id).
output "origin_access_control_id" {
  description = "Origin access control ID attached to S3 origins, whether provided or created by the module."
  value       = local.origin_access_control_id
}

# ---------------------------------------------------------------------------
# Distribution state
# ---------------------------------------------------------------------------

# distribution_status
# The deployment status of the distribution: "InProgress" or "Deployed".
# When wait_for_deployment = true, apply blocks until this reads "Deployed".
# Useful for monitoring pipelines or for diagnostic purposes.
output "distribution_status" {
  description = "Current deployment status of the CloudFront distribution."
  value       = aws_cloudfront_distribution.this.status
}

# distribution_etag
# The HTTP ETag returned by the CloudFront API for this distribution config.
# Required when making direct API calls to update or delete the distribution
# (the API uses ETags for optimistic concurrency control).
output "distribution_etag" {
  description = "Current ETag for the CloudFront distribution configuration."
  value       = aws_cloudfront_distribution.this.etag
}

# distribution_aliases
# The set of custom domain names currently configured on the distribution.
# Useful for verification or for feeding into other modules without re-stating
# the aliases variable.
output "distribution_aliases" {
  description = "Aliases configured on the CloudFront distribution."
  value       = aws_cloudfront_distribution.this.aliases
}

# distribution_comment
# The descriptive label shown in the AWS Console.
# Either the value of var.comment, or the auto-generated distribution name.
output "distribution_comment" {
  description = "Comment configured on the CloudFront distribution."
  value       = aws_cloudfront_distribution.this.comment
}

# ---------------------------------------------------------------------------
# Structured output object
# ---------------------------------------------------------------------------

# distribution
# A single object collecting the most commonly needed distribution attributes.
# Some callers prefer a structured object over individual outputs because it
# simplifies passing the full "distribution context" between modules with a
# single variable.
# Example usage:
#   module.cloudfront.distribution.domain_name
#   module.cloudfront.distribution.hosted_zone_id
output "distribution" {
  description = "Structured distribution metadata for downstream modules."
  value = {
    id             = aws_cloudfront_distribution.this.id
    arn            = aws_cloudfront_distribution.this.arn
    domain_name    = aws_cloudfront_distribution.this.domain_name
    hosted_zone_id = aws_cloudfront_distribution.this.hosted_zone_id
    status         = aws_cloudfront_distribution.this.status
    etag           = aws_cloudfront_distribution.this.etag
    aliases        = aws_cloudfront_distribution.this.aliases
    comment        = aws_cloudfront_distribution.this.comment
  }
}

# ---------------------------------------------------------------------------
# S3 origin policy utilities
# ---------------------------------------------------------------------------

# s3_origin_bucket_names
# A map from each S3 origin ID to its resolved S3 bucket name.
# The bucket name is taken from s3_config.bucket_name when provided, or
# derived from the domain_name field otherwise.
# Expose this so callers can verify which bucket names the module resolved,
# or use them in additional IAM / replication resources.
output "s3_origin_bucket_names" {
  description = "Map of S3 origin IDs to resolved bucket names when available."
  value       = local.s3_origin_bucket_names
}

# s3_origin_bucket_policy_documents
# A map from each managed S3 bucket name to the JSON text of the generated
# bucket policy.
# The policy grants CloudFront OAC read access and denies any non-HTTPS
# (non-SigV4) request to the bucket.
#
# This output is useful for:
#   - Auditing: inspect the exact policy being applied to each bucket.
#   - Overriding: copy the JSON as a starting point if you need to manage
#     the policy yourself (set s3_config.manage_bucket_policy = false).
#
# The for expression iterates over the data.aws_iam_policy_document map and
# extracts the rendered JSON (.json attribute) for each entry.
output "s3_origin_bucket_policy_documents" {
  description = "Generated S3 bucket policy JSON documents keyed by bucket name for CloudFront OAC access and TLS-only enforcement."
  value = {
    for bucket_name, policy in data.aws_iam_policy_document.s3_origin_bucket_policy :
    bucket_name => policy.json
  }
}
