name: Frontend CI
on:
  pull_request:
    branches: [dev, prod]
    paths: ["frontend/web/**"]
  # push:
  #   branches: ["feature/**"]
  #   paths: ["frontend/**"]
jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      #- name: Create .env.local
        # run: |
        #   cat <<'EOF' > .env.local
        #   VITE_COGNITO_USER_POOL_ID=${{ secrets.VITE_COGNITO_USER_POOL_ID }}
        #   VITE_COGNITO_USER_POOL_CLIENT_ID=${{ secrets.VITE_COGNITO_USER_POOL_CLIENT_ID }}
        #   VITE_API_URL=${{ secrets.VITE_API_URL }}
        #   EOF
      - run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - run: npm run lint
      - run: npm run test